version: '3.8'

services:
  app:
    image: ghcr.io/wenwen12345/uni-web:latest
    container_name: uni-web
    ports:
      - "8000:8000"
    environment:
      - DEV_MODE=false
      - TZ=Asia/Shanghai
    volumes:
      - ./src/backend/app.yaml:/app/app.yaml
    restart: unless-stopped
    networks:
      - uni-web-network

  uni-api:
    container_name: uni-api
    image: yym68686/uni-api:latest
    environment:
      - CONFIG_URL=http://uni-web:8000/app.yaml
    ports:
      - 8001:8000
    restart: unless-stopped
    networks:
      - uni-web-network

networks:
  uni-web-network:
    driver: bridge